name       : korganizer
version    : 18.08.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/korganizer-18.08.0.tar.xz : e146823da56fb0cf8978fdae4d3f1ae78e80dba894cee1ba3e52ca91a8692e62
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : office
summary    : KDE calendar and scheduling program
description: |
    KOrganizer provides management of events and tasks, alarm notification, web export, network transparent handling of data, group scheduling, import and export of calendar files and more. It is able to work together with a wide variety of groupware servers, for example Kolab, Open-Xchange, Citadel or OpenGroupware.org.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5UiTools)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - incidenceeditor-devel
    - kcalcore-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kservice-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - openldap-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
