name       : korganizer
version    : 22.04.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/korganizer-22.04.0.tar.xz : 51937ec5254e3f5347d5f0b3cab36d831dae430607467e58bea5c4c879b90d8b
homepage   : https://kde.org/applications/office/org.kde.korganizer
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : KDE calendar and scheduling program
description: |
    KOrganizer provides management of events and tasks, alarm notification, web export, network transparent handling of data, group scheduling, import and export of calendar files and more. It is able to work together with a wide variety of groupware servers, for example Kolab, Open-Xchange, Citadel or OpenGroupware.org.
builddeps  :
    - pkgconfig(x11)
    - akonadi-calendar-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdoctools-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmailtransport-devel
    - knewstuff-devel
    - knotifications-devel
    - kontactinterface-devel
    - kparts-devel
    - kuserfeedback-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
