name       : korganizer
version    : 23.04.2
release    : 69
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/korganizer-23.04.2.tar.xz : 513b006256a5a20f5439289a816016dd3ad0b5dcad9a9dbc7d22f37ef3c5ee92
homepage   : https://kde.org/applications/office/org.kde.korganizer
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : KDE calendar and scheduling program
description: |
    KOrganizer provides management of events and tasks, alarm notification, web export, network transparent handling of data, group scheduling, import and export of calendar files and more. It is able to work together with a wide variety of groupware servers, for example Kolab, Open-Xchange, Citadel or OpenGroupware.org.
builddeps  :
    - pkgconfig(x11)
    - akonadi-calendar-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - calendarsupport-devel
    - eventviews-devel
    - incidenceeditor-devel
    - kcmutils-devel
    - kcontacts-devel
    - kcrash-devel
    - kdoctools-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmailtransport-devel
    - knewstuff-devel
    - knotifications-devel
    - kontactinterface-devel
    - kparts-devel
    - ktextaddons-devel
    - kuserfeedback-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
