name       : korganizer
version    : 19.12.2
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/korganizer-19.12.2.tar.xz : d8c61b38ffc60157988e707b155d3bbdacbc2a5defc906cbe435e02d1b394c03
homepage   : https://kde.org/applications/office/org.kde.korganizer
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : KDE calendar and scheduling program
description: |
    KOrganizer provides management of events and tasks, alarm notification, web export, network transparent handling of data, group scheduling, import and export of calendar files and more. It is able to work together with a wide variety of groupware servers, for example Kolab, Open-Xchange, Citadel or OpenGroupware.org.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5UiTools)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-notes-devel
    - akonadi-search-devel
    - calendarsupport-devel
    - eventviews-devel
    - extra-cmake-modules
    - incidenceeditor-devel
    - kcalutils-devel
    - kcmutils-devel
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - knotifications-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - libkdepim-devel
    - openldap-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
